mongo:
  app:
    name: mongo-app-dev
  containers:
    name: mongo-dev
    image: mongo
    port: 27017
  pvc:
    name: mongo-pvc-dev
    storage: 512Mi
  config:
    name: mongo-config-dev
  secret:
    name: mongo-secret-dev
    data:
      mongoUser: cm9vdA==
      mongoPassword: ZXhhbXBsZQ==

springboot:
  app:
    name: spring-boot-app-dev
    nodePort: 31000
  containers:
    name: spring-boot-app-dev
    image: json-schema-validator:0.0.1-SNAPSHOT
    port: 8080
  config:
    name: spring-boot-config-dev
    data:
      env: dev
