apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.springboot.app.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.springboot.app.name }}
  ports:
    - protocol: TCP
      name: spring-boot-port
      port: {{ .Values.springboot.containers.port }}
      targetPort: {{ .Values.springboot.containers.port }}
      nodePort: {{ .Values.springboot.app.nodePort }}
