apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secret.name }}
type: Opaque
data:
  mongo-user: {{ .Values.mongo.secret.data.mongoUser }}
  mongo-password: {{ .Values.mongo.secret.data.mongoPassword }}