apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.pvc.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.storage }}